# Generated by Django 2.0.4 on 2018-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsheading',
            options={'verbose_name_plural': 'NewsHeadings'},
        ),
        migrations.AddField(
            model_name='newsheading',
            name='short_name',
            field=models.CharField(default='Du', max_length=2),
            preserve_default=False,
        ),
    ]
