# Generated by Django 2.0.4 on 2018-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180412_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='before_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='current_url',
            field=models.CharField(default='AIU', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='next_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
