# Generated by Django 2.0.4 on 2018-04-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_news_news_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='before_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='next_url',
        ),
        migrations.AlterField(
            model_name='news',
            name='attachement_titles',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='attachement_urls',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
