# Generated by Django 2.0.4 on 2018-04-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180412_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='url_params',
        ),
    ]
