# Generated by Django 2.0.4 on 2018-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_newsheading_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheading',
            name='attachement_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
