# Generated by Django 2.0.4 on 2018-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_newsheading_attachement_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject_code', models.IntegerField(unique=True)),
                ('teacher_name', models.CharField(max_length=50)),
                ('attended_students', models.CharField(max_length=300, null=True)),
                ('academic_credit', models.CharField(max_length=100, null=True)),
                ('academic_credit_num', models.IntegerField()),
                ('target_class', models.CharField(max_length=100)),
                ('target_term', models.CharField(max_length=100)),
                ('class_number', models.IntegerField()),
                ('target_hour', models.CharField(max_length=200)),
                ('target_place', models.CharField(max_length=150)),
                ('published_date', models.DateTimeField()),
                ('abstract', models.CharField(max_length=1000)),
                ('positioning', models.CharField(max_length=1000)),
                ('lecture_content', models.CharField(max_length=1000)),
                ('lecture_processing', models.CharField(max_length=1000)),
                ('performance_target', models.CharField(max_length=1000)),
                ('valuation_basis', models.CharField(max_length=1000)),
                ('instruction_out_learning', models.CharField(max_length=1000, null=True)),
                ('keyword', models.CharField(max_length=500, null=True)),
                ('text_book', models.CharField(max_length=500, null=True)),
                ('study_aid_books', models.CharField(max_length=500, null=True)),
                ('professor_email', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Syllabus',
            },
        ),
    ]
