# Generated by Django 2.0.4 on 2018-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='attended_students',
            new_name='target_participants',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
