# Generated by Django 2.0.4 on 2018-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180423_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='subject_code',
            field=models.IntegerField(),
        ),
    ]
