# Generated by Django 2.0.4 on 2018-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180424_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='academic_credit_num',
            field=models.FloatField(),
        ),
    ]
