# Generated by Django 2.0.4 on 2018-04-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180426_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='academic_credit',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='academic_credit_num',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='target_participants',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='academic_credit_infos',
            field=models.CharField(default='aiueo', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.IntegerField(choices=[(21, '情報工学部\u3000知能情報工学科'), (22, '情報工学部\u3000情報・通信工学科'), (23, '情報工学部\u3000知的システム工学科'), (24, '情報工学部\u3000物理情報工学科'), (25, '情報工学部\u3000生命情報工学科')], default=21),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_year',
            field=models.IntegerField(choices=[(1, '1回生'), (2, '2回生'), (3, '3回生'), (4, '4回生')], default=1),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='day',
            field=models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜')], default=0),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='period',
            field=models.IntegerField(choices=[(0, '1限'), (1, '2限'), (2, '3限'), (3, '4限'), (4, '5限')], default=4),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='quarter',
            field=models.IntegerField(choices=[(0, '第1クオーター'), (1, '第2クオーター'), (2, '第3クオーター'), (3, '第4クオーター')], default=0),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
