# Generated by Django 2.0.4 on 2018-04-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180430_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='text_book',
            new_name='text_books',
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
