# Generated by Django 2.0.4 on 2018-04-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180430_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='target_class',
            new_name='target_school_year',
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
