# Generated by Django 2.0.4 on 2018-05-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180509_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='absent_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='late_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
