# Generated by Django 2.0.4 on 2018-05-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180514_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='attachement_titles',
            new_name='attachment_titles',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='attachement_urls',
            new_name='attachment_urls',
        ),
        migrations.RenameField(
            model_name='newsheading',
            old_name='attachement_count',
            new_name='attachment_count',
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
