# Generated by Django 2.0.4 on 2018-10-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180514_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.IntegerField(choices=[(200, '情報工学部\u3000情工１類\u3000Ⅰクラス'), (201, '情報工学部\u3000情工１類\u3000Ⅱクラス'), (202, '情報工学部\u3000情工２類\u3000Ⅲクラス'), (203, '情報工学部\u3000情工３類\u3000Ⅳクラス'), (204, '情報工学部\u3000情工３類\u3000Ⅴクラス'), (205, '情報工学部\u3000知能情報工学科'), (206, '情報工学部\u3000知能情報工学科\u3000知能情報工学科（編入）'), (207, '情報工学部\u3000電子情報工学科'), (208, '情報工学部\u3000電子情報工学科\u3000電子情報工学科（編入）'), (209, '情報工学部\u3000システム創成情報工学科\u3000システム創成情報工学科'), (210, '情報工学部\u3000システム創成情報工学科\u3000システム創成情報工学科（編入）'), (211, '情報工学部\u3000機械情報工学科\u3000機械情報工学科'), (212, '情報工学部\u3000機械情報工学科\u3000機械情報工学科（編入）'), (213, '情報工学部\u3000生命情報工学科\u3000生命情報工学科'), (214, '情報工学部\u3000生命情報工学科\u3000生命情報工学科（編入）')], default=205),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_year',
            field=models.IntegerField(choices=[(0, '1回生'), (1, '2回生'), (2, '3回生'), (3, '4回生')], default=0),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
