# Generated by Django 2.0.4 on 2018-05-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180509_1608'),
        ('api', '0025_auto_20180514_2250'),
    ]

    operations = [
    ]
