# Generated by Django 2.0.4 on 2018-05-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20180515_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='abstract',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instruction_out_learning',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_content',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_processing',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='performance_target',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='positioning',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='professor_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_school_year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='valuation_basis',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.IntegerField(choices=[(200, '情報工学部\u3000情工１類\u3000Ⅰクラス'), (201, '情報工学部\u3000情工１類\u3000Ⅱクラス'), (202, '情報工学部\u3000情工２類\u3000Ⅲクラス'), (203, '情報工学部\u3000情工３類\u3000Ⅳクラス'), (204, '情報工学部\u3000情工３類\u3000Ⅴクラス'), (205, '情報工学部\u3000知能情報工学科'), (206, '情報工学部\u3000知能情報工学科\u3000知能情報工学科（編入）'), (207, '情報工学部\u3000電子情報工学科'), (208, '情報工学部\u3000電子情報工学科\u3000電子情報工学科（編入）'), (209, '情報工学部\u3000システム創成情報工学科\u3000システム創成情報工学科'), (210, '情報工学部\u3000システム創成情報工学科\u3000システム創成情報工学科（編入）'), (211, '情報工学部\u3000機械情報工学科\u3000機械情報工学科'), (212, '情報工学部\u3000機械情報工学科\u3000機械情報工学科（編入）'), (213, '情報工学部\u3000生命情報工学科\u3000生命情報工学科'), (214, '情報工学部\u3000生命情報工学科\u3000生命情報工学科（編入）')], default=205),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
