# Generated by Django 2.0.4 on 2018-10-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20181012_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='abstract',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='academic_credit_infos',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instruction_out_learning',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='keywords',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_processing',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='performance_target',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='positioning',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='professor_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='study_aid_books',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_school_year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='target_term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='teacher_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='text_books',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='valuation_basis',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
