# Generated by Django 2.0.4 on 2018-05-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180516_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='study_aid_books',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
