# Generated by Django 2.0.4 on 2018-06-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180601_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_year',
            field=models.IntegerField(choices=[(0, '1回生'), (1, '2回生'), (2, '3回生'), (3, '4回生')], default=0),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
