# Generated by Django 2.0.4 on 2018-08-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180704_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
