# Generated by Django 2.0.4 on 2018-10-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180807_0059'),
        ('api', '0028_auto_20181012_2330'),
    ]

    operations = [
    ]
