# Generated by Django 2.0.4 on 2018-10-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20181014_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='unique_code',
            field=models.IntegerField(choices=[(200, '情報工学部\u3000情工１類\u3000Ⅰクラス'), (201, '情報工学部\u3000情工１類\u3000Ⅱクラス'), (202, '情報工学部\u3000情工２類\u3000Ⅲクラス'), (203, '情報工学部\u3000情工３類\u3000Ⅳクラス'), (204, '情報工学部\u3000情工３類\u3000Ⅴクラス'), (205, '情報工学部\u3000知能情報工学科'), (206, '情報工学部\u3000知能情報工学科\u3000知能情報工学科（編入）'), (207, '情報工学部\u3000電子情報工学科'), (208, '情報工学部\u3000電子情報工学科\u3000電子情報工学科（編入）'), (209, '情報工学部\u3000システム創成情報工学科\u3000システム創成情報工学科'), (210, '情報工学部\u3000システム創成情報工学科\u3000システム創成情報工学科（編入）'), (211, '情報工学部\u3000機械情報工学科\u3000機械情報工学科'), (212, '情報工学部\u3000機械情報工学科\u3000機械情報工学科（編入）'), (213, '情報工学部\u3000生命情報工学科\u3000生命情報工学科'), (214, '情報工学部\u3000生命情報工学科\u3000生命情報工学科（編入）'), (215, '大学院情報工学府博士前期課程\u3000情報創成工学専攻\u3000情報創成工学専門分野'), (216, '大学院情報工学府博士前期課程\u3000先端情報工学専攻\u3000知能情報工学専門分野'), (217, '大学院情報工学府博士前期課程\u3000先端情報工学専攻\u3000電子情報工学専門分野'), (218, '大学院情報工学府博士前期課程\u3000学際情報工学専攻\u3000システム創成情報工学専門分野'), (219, '大学院情報工学府博士前期課程\u3000学際情報工学専攻\u3000生命情報工学専門分野'), (220, '大学院情報工学府博士前期課程\u3000学際情報工学専攻\u3000機械情報工学専門分野')], db_index=True, default=200),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='unique_code',
            field=models.IntegerField(choices=[(0, '学部1年'), (1, '学部2年'), (2, '学部3年'), (3, '学部4年'), (4, '修士1年'), (5, '修士2年')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
