# Generated by Django 2.0.4 on 2018-10-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20181014_0156'),
        ('api', '0049_auto_20181013_2228'),
    ]

    operations = [
    ]
