# Generated by Django 2.0.4 on 2018-10-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_merge_20181014_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departmentZ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_yearZ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.SchoolYear'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
