# Generated by Django 2.0.4 on 2018-10-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20181014_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_year_id',
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
