# Generated by Django 2.0.4 on 2018-10-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20181014_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_yearZ',
            new_name='school_year',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='departmentZ',
            new_name='department',
        ),
    ]
