# Generated by Django 2.0.4 on 2018-10-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20181014_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SchoolYear'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
