# Generated by Django 2.0.4 on 2018-10-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20181014_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolyear',
            old_name='unique_code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='unique_code',
            new_name='id',
        ),
    ]
