# Generated by Django 2.0.4 on 2019-05-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20190505_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_content',
            field=models.CharField(max_length=4500),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
