# Generated by Django 2.0.4 on 2019-05-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20190515_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimpression',
            old_name='p_and_d_opinion',
            new_name='request_pd',
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
