# Generated by Django 2.0.4 on 2019-05-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20190515_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimpression',
            name='reply',
            field=models.CharField(default='未回答', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Syllabus'),
        ),
    ]
